######################################################################
# Automatically generated by qmake (2.01a) Mon May 9 17:11:49 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
QT += widgets
