######################################################################
# Automatically generated by qmake (2.01a) Mon May 9 17:11:45 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += camer_ops.h camera_win.h v4l2.h
FORMS += camera.ui
SOURCES += camer_ops.cpp camera_win.cpp main.cpp v4l2.c
QT += widgets
