######################################################################
# Automatically generated by qmake (2.01a) Mon May 9 17:11:50 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += led.h
FORMS += led.ui
SOURCES += led.cpp main.cpp
QT += widgets
