#!/bin/sh
case "$1" in
  start)
        if [ -e /etc/asound.state ] ; then
                alsactl restore -f /etc/asound.state                     
                sync                
        fi          
        ;;
  stop)   
        ;;
  restart|reload)
        ;;       
  *)      
        echo "Usage: $0 {start|stop|restart}"
        exit 1                               
esac          
    
exit $?
