#!/bin/sh
case "$1" in
  start)
	#ifconfig eth0 hw ether 00:0C:29:36:97:20
	ifup -a
	#wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
	#udhcpc -i  wlan0
        ;;
  stop)   
        ;;
  restart|reload)
        ;;       
  *)      
        echo "Usage: $0 {start|stop|restart}"
        exit 1                               
esac          
    
exit $?
