######################################################################
# Automatically generated by qmake (2.01a) Mon May 9 17:11:50 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += uart.h uart_thread.h
FORMS += uart.ui
SOURCES += main.cpp uart.cpp uart_thread.cpp
QT += widgets
